Repository TylerAdamMartinez/Optimal-Accessibility, pull requests merged in 2022-08, with the labels that each got.

#48 [Pages] Add guest page
  Application/package-lock.json
  Application/package.json
  Application/src/App.js
  Application/src/Components/NavBar.css
  Application/src/Components/NavBar.js
  Application/src/Pages/DashBoard/GuestDashboard.css
  Application/src/Pages/DashBoard/GuestDashboard.js
  Application/src/Pages/LoginPage.css
  Application/src/Pages/LoginPage.js
  Application/src/Pages/RegistrationPage.css
Labels: enhancement

#49 [firebase] Add firebase hosting
  Application/.firebaserc
  Application/firebase.json
  Application/public/404.html
Labels: enhancement

#50 [Application] Add Dockerfile
  Application/.dockerignore
  Application/Dockerfile
  Application/nginx/nginx.conf
Labels: enhancement

#51 [Pages] Refactor pages
  Application/src/App.css
  Application/src/App.js
  Application/src/Components/LoginPageBackground.js
  Application/src/Components/NavBar.js
  Application/src/Images/Google__G__Logo.svg
  Application/src/Pages/Home/LoginPage.css
  Application/src/Pages/Home/LoginPage.js
  Application/src/Pages/LoginPage.css
  Application/src/Pages/LoginPage.js
  Application/src/Pages/NotFound404ErrorPage.css
  Application/src/Pages/NotFound404ErrorPage/NotFound404ErrorPage.css
  Application/src/Pages/NotFound404ErrorPage/NotFound404ErrorPage.js
  Application/src/Pages/RegistrationPage.css
  Application/src/Pages/RegistrationPage.js
  Application/src/Pages/SettingsPage/SettingsPage.css
  Application/src/Pages/SettingsPage/SettingsPage.js
  Docs/Assets/Logo/DuckHead.svg
Labels: refactor

#53 [README] Update how to run section
  Application/README.md
  README.md
Labels: documentation

#52 [GuestMode]: Add help info
  Application/src/Components/NavBar.css
  Application/src/Components/NavBar.js
  Application/src/Pages/DashBoard/GuestDashboard.css
Labels: enhancement, refactor

#54 [Application] Add firebase and google authentication
  Application/package-lock.json
  Application/package.json
  Application/src/App.js
  Application/src/Components/PrivateRoutes.js
  Application/src/FirebaseConfig.js
  Application/src/Pages/Home/LoginPage.css
  Application/src/Pages/Home/LoginPage.js
Labels: bug, enhancement, refactor

#55 [HomePage] Restyled Home Page
  Application/src/App.js
  Application/src/Images/background.svg
  Application/src/Pages/Home/HomePage.css
  Application/src/Pages/Home/HomePage.js
Labels: enhancement

#56 [src] Implement firebase posters CRUD operations
  Application/src/Components/NavBar.css
  Application/src/Components/NavBar.js
  Application/src/Pages/DashBoard/DashBoard.js
  Application/src/Pages/DashBoard/MyPoster.js
  Application/src/Pages/DashBoard/OverallAccessibilitySection.js
  Application/src/Pages/Home/HomePage.css
  Application/src/Pages/Home/HomePage.js
  Application/src/Pages/SettingsPage/SettingsPage.css
  Application/src/Pages/SettingsPage/SettingsPage.js
Labels: bug, refactor

#57 Add PDF Generation
  Application/package-lock.json
  Application/package.json
  Application/src/Components/NavBar.js
  Application/src/Utils/CreatePDF.js
Labels: enhancement, refactor

#58 [MyPosters][NavBar] Popups are now clickoutable
  Application/src/Components/NavBar.css
  Application/src/Components/NavBar.js
  Application/src/Pages/DashBoard/MyPoster.css
  Application/src/Pages/DashBoard/MyPoster.js
Labels: bug

#59 [Application] Switch caching & Improve loading notifications
  Application/src/Components/NavBar.css
  Application/src/Components/NavBar.js
  Application/src/Pages/DashBoard/DashBoard.js
  Application/src/Pages/DashBoard/MyPoster.js
Labels: enhancement

#60 Final Adjustments
  Application/src/Pages/Home/HomePage.css
Labels: refactor
