Repository TylerAdamMartinez/Optimal-Accessibility, pull requests merged in 2022-07, with the labels that each got.

#20 [UserRepo] Fix: HttpgGet Poster AccessibityScore from API
  API/.vs/API/xs/UserPrefs.xml
  API/OptimalAccessibility.API/Controllers/AuthController.cs
  API/OptimalAccessibility.API/Controllers/UserController.cs
  API/OptimalAccessibility.API/Repositories/AuthRepo.cs
  API/OptimalAccessibility.API/Repositories/UsersRepo.cs
  API/OptimalAccessibility.Domain/Enum/DatabaseResultTypes.cs
  API/OptimalAccessibility.Domain/Models/DataTransferObjects/PosterDTO.cs
  Application/src/Components/NavBar.css
Labels: bug

#21 [UsersRepo] Fix HttpPost Get Overall Accessibility Score Zeroing Out Bug
  API/OptimalAccessibility.API/Repositories/UsersRepo.cs
Labels: bug

#22 [/API] Improve User Authentication Security
  API/.vs/API/xs/project-cache/OptimalAccessibility.API-Debug.json
  API/.vs/API/xs/project-cache/OptimalAccessibility.Domain-Debug.json
  API/.vs/API/xs/project-cache/OptimalAccessibility.Tests-Debug.json
  API/OptimalAccessibility.API/Controllers/AuthController.cs
  API/OptimalAccessibility.API/Controllers/UserController.cs
  API/OptimalAccessibility.API/OptimalAccessibility.API.csproj
  API/OptimalAccessibility.API/Program.cs
  API/OptimalAccessibility.API/Repositories/AuthRepo.cs
  API/OptimalAccessibility.API/Repositories/UsersRepo.cs
  API/OptimalAccessibility.API/appsettings.json
  API/OptimalAccessibility.Application/Repositories/IAuthRepo.cs
  API/OptimalAccessibility.Application/Repositories/IUserRepo.cs
  API/OptimalAccessibility.Domain/Models/Auth/LoginUserBody.cs
  API/OptimalAccessibility.Domain/Models/Auth/LoginUserResponse.cs
  API/OptimalAccessibility.Domain/Models/Auth/RegisterNewUserBody.cs
  API/OptimalAccessibility.Domain/Models/Auth/UpdateUserBody.cs
  API/OptimalAccessibility.Domain/OptimalAccessibility.Domain.csproj
  API/OptimalAccessibility.Tests/Controllers/UserControllerTest.cs
Labels: bug, enhancement

#24 [NavBar] feat: Create add new poster menu
  API/OptimalAccessibility.Tests/Controllers/UserControllerTest.cs
  Application/package-lock.json
  Application/src/Components/NavBar.css
  Application/src/Components/NavBar.js
  README.md
Labels: enhancement

#25 [Application] feat: Add routes and individual pages to react site
  Application/package-lock.json
  Application/package.json
  Application/public/Optimal-Accessibility-Logo.svg
  Application/public/index.html
  Application/src/App.css
  Application/src/App.js
  Application/src/Components/NavBar.css
  Application/src/Components/NavBar.js
  Application/src/DashBoard.js
  Application/src/LoginPage.css
  Application/src/LoginPage.js
  Application/src/NotFound404ErrorPage.css
  Application/src/NotFound404ErrorPage.js
  Application/src/RegistrationPage.css
  Application/src/RegistrationPage.js
Labels: enhancement

#26 [Utils] color: Color contrast is adequately scored
  Application/package-lock.json
  Application/package.json
  Application/src/Utils/Color.js
Labels: enhancement

#27 [Utils] structure: Add rating of poster structure
  Application/src/Utils/Color.js
  Application/src/Utils/Structure.js
Labels: enhancement

#28 [/Application][/API] Integrate backend with frontend
  .gitignore
  API/.vs/API/FileContentIndex/60b0e53c-98cf-4d3f-9649-81298cdba8fd.vsidx
  API/.vs/API/FileContentIndex/read.lock
  API/OptimalAccessibility.API/Controllers/AuthController.cs
  API/OptimalAccessibility.API/Controllers/UserController.cs
  API/OptimalAccessibility.API/Program.cs
  Application/package.json
  Application/src/App.js
  Application/src/Components/MyPoster.js
  Application/src/Components/MyPostersSection.js
  Application/src/DashBoard.js
  Application/src/LoginPage.js
  Application/src/Pages/DashBoard.js
  Application/src/Pages/LoginPage.css
  Application/src/Pages/LoginPage.js
  Application/src/Pages/NotFound404ErrorPage.css
  Application/src/Pages/NotFound404ErrorPage.js
  Application/src/Pages/RegistrationPage.css
  Application/src/Pages/RegistrationPage.js
  README.md
Labels: enhancement

#29 [Application] Integrate backend Image uploading and downloading
  Application/src/App.js
  Application/src/Components/MyPoster.js
  Application/src/Components/MyPostersSection.js
  Application/src/Components/NavBar.js
  Application/src/Components/PrivateRoutes.js
  Application/src/Pages/LoginPage.js
Labels: enhancement

#30 [Application] Move Jwt token to SameSite strict cookie
  .gitignore
  Application/package-lock.json
  Application/package.json
  Application/src/Components/AccessibilityBarGraphData.js
  Application/src/Components/MyPoster.js
  Application/src/Components/NavBar.js
  Application/src/Components/PrivateRoutes.js
  Application/src/Pages/DashBoard.js
  Application/src/Pages/LoginPage.js
Labels: bug

#32 [Utils]: Refactor text rating and adjust scoring
  Application/package-lock.json
  Application/src/Utils/Structure.js
  Application/src/Utils/TestImageComponent.js
  Application/src/Utils/Text.js
  Application/src/Utils/assets/bad.jpg
  Application/src/Utils/assets/good.jpg
Labels: refactor

#33 [NavBar]: Add initial poster rating function call
  Application/src/Components/NavBar.js
Labels: enhancement, integration

#34 [Pages] Update web application user interface
  Application/src/Components/AccessibilityBarGraphData.js
  Application/src/Components/BarGraph.js
  Application/src/Components/HelpPage.css
  Application/src/Components/MyPoster.css
  Application/src/Components/MyPoster.js
  Application/src/Components/MyPostersSection.css
  Application/src/Components/NavBar.css
  Application/src/Components/NavBar.js
  Application/src/Components/OverallAccessibilitySection.css
  Application/src/Pages/LoginPage.css
  Application/src/Pages/NotFound404ErrorPage.css
  Application/src/Pages/RegistrationPage.css
Labels: refactor

#31 [UsersRepo] Fix CRUD operations for posters
  API/OptimalAccessibility.API/Controllers/UserController.cs
  API/OptimalAccessibility.API/Repositories/UsersRepo.cs
  API/OptimalAccessibility.Application/Repositories/IUserRepo.cs
  Application/src/Components/MyPoster.js
Labels: bug

#36 [NavBar]: Add help info text
  Application/package-lock.json
  Application/package.json
  Application/src/Components/HelpPage.js
  Application/src/Components/NavBar.js
Labels: enhancement

#37 [API][Application] Add PDF reporting
  API/OptimalAccessibility.API/Controllers/AuthController.cs
  API/OptimalAccessibility.API/Controllers/UserController.cs
  API/OptimalAccessibility.API/Program.cs
  API/OptimalAccessibility.API/Repositories/UsersRepo.cs
  API/OptimalAccessibility.Application/OptimalAccessibility.Application.csproj
  API/OptimalAccessibility.Application/ReportTemplates/OptimalAccessibilityReportTemplate.hbs
  API/OptimalAccessibility.Application/Repositories/IReporting.cs
  API/OptimalAccessibility.Application/Repositories/IUserRepo.cs
  API/OptimalAccessibility.Application/Services/ReportingsService.cs
  API/OptimalAccessibility.Domain/Models/Auth/LoginUserResponse.cs
  API/OptimalAccessibility.Domain/Models/DataTransferObjects/OptimalAccessibilityReportDetails.cs
  API/OptimalAccessibility.Domain/Models/DataTransferObjects/PosterReportDetails.cs
  API/OptimalAccessibility.Tests/Controllers/UserControllerTest.cs
  API/OptimalAccessibility.Tests/DatabaseTest.cs
  API/OptimalAccessibility.Tests/OptimalAccessibility.Tests.csproj
  API/README.md
  Application/README.md
  Application/src/Components/NavBar.js
  Application/src/Pages/LoginPage.js
  README.md
Labels: enhancement

#38 [Utils]: Add edge case catching
  Application/src/Utils/Color.js
  Application/src/Utils/Structure.js
  Application/src/Utils/Text.js
  Application/src/Utils/assets/AdPoster.jpg
  Application/src/Utils/assets/Poster.png
  Application/src/Utils/assets/Poster2.jpg
  Application/src/Utils/assets/bad.jpg
  Application/src/Utils/assets/good.jpg
  Application/src/Utils/assets/iceCreamAd.jpg
  Application/src/Utils/word_bank_file.txt
Labels: bug, refactor

#40 [App] deps: Add dependency for github pages hosting
  Application/package-lock.json
  Application/package.json
Labels: enhancement

#43 [README] Update image links in docs
  API/README.md
  Application/README.md
  README.md
Labels: documentation

#44 [Styles]: Add faded background to popup menus
  Application/src/Components/NavBar.css
  Application/src/Components/NavBar.js
  Application/src/Pages/DashBoard/MyPoster.css
  Application/src/Pages/DashBoard/MyPoster.js
  Application/src/Pages/SettingsPage.css
  Application/src/Pages/SettingsPage.js
Labels: refactor

#45 [Pages] Add push notifications & Fix Update/Delete User functions
  API/OptimalAccessibility.API/Controllers/AuthController.cs
  API/OptimalAccessibility.API/Controllers/UserController.cs
  API/OptimalAccessibility.API/Repositories/UsersRepo.cs
  API/OptimalAccessibility.Application/Repositories/IUserRepo.cs
  API/OptimalAccessibility.Domain/Models/Auth/UpdateUserBody.cs
  Application/package-lock.json
  Application/package.json
  Application/src/Components/NavBar.js
  Application/src/Pages/DashBoard/MyPoster.css
  Application/src/Pages/DashBoard/MyPoster.js
  Application/src/Pages/LoginPage.js
  Application/src/Pages/NotFound404ErrorPage.js
  Application/src/Pages/RegistrationPage.js
  Application/src/Pages/SettingsPage.css
  Application/src/Pages/SettingsPage.js
Labels: enhancement

#47 [*.css] Refactoring of *.css files
  Application/package.json
  Application/public/Optimal-Accessibility-Logo.svg
  Application/public/favicon.ico
  Application/public/logo512.png
  Application/src/App.css
  Application/src/Components/HelpPage.css
  Application/src/Components/NavBar.css
  Application/src/Components/NavBar.js
  Application/src/Images/Optimal-Accessibility-Logo.png
  Application/src/Pages/DashBoard/MyPoster.css
  Application/src/Pages/DashBoard/MyPoster.js
  Application/src/Pages/DashBoard/MyPostersSection.css
  Application/src/Pages/DashBoard/MyPostersSection.js
  Application/src/Pages/DashBoard/OverallAccessibilitySection.css
  Application/src/Pages/LoginPage.css
  Application/src/Pages/NotFound404ErrorPage.css
  Application/src/Pages/RegistrationPage.css
  Application/src/Pages/SettingsPage.css
  Application/src/index.css
Labels: refactor
